### ISSUE TITLE
Pincodes of Indian City

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#506] opened 2021-06-26 01:52 UTC
---
Title: Pincodes of Indian City
About: It's a GUI script 
Name: Akash Ramanand Rajak
Label: feature request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

In this script,
will create an application that will allow user to get all the Pin Codes, that are running in any city in India.
And also get that city is located in which state.

for eg., suppose city selected is 
ROHTAK which is in Haryana.
Then the script will tells us about all the Pin Codes that are running in the city ROHTAK,
which are 124001, 124010, 124021 and 124022.

**Comment by akash435** [comment] 2021-06-26 01:52
@prathimacode-hub , please assign this to me under LGM SOC, can add this under GUIScripts.

**Comment by Debashish-hub** [comment] 2021-06-26 04:11
I think you have already done Indian University NIRF Ranking  @akash435 
Please correct the issue template

**Comment by akash435** [comment] 2021-06-26 04:12
Sorry, i forgot to changed the title, now i have changed please check it and assign if OK.

**Comment by Debashish-hub** [comment] 2021-06-26 04:18
Its Ok. The issue is assigned to you @akash435

**Closed** 2021-06-26 09:29 UTC
Labels: Assigned, LGMSOC21
