### ISSUE TITLE
Simple Oddly Satisfying Animation/Game using PyGame

### ISSUE THREAD

**Issue by AK-Subodh** [prathimacode-hub/Awesome_Python_Scripts#67] opened 2021-06-10 02:55 UTC
Title | About | Name | Label | Assignee
----- | ------ | ------- | ------ | ----------
Oddly Satisfying Game | Various Elements keep moving around the screen bouncing off the surfaces. User input affects one of them | AK-Subodh | Feature Request | 

Define You:

- [x] LGM-SOC'21 Participant

Solution I'd Follow:
Use of simple collision mechanics. All the type 2 element are in random motion. Type1 element is under the effect of gravity and can be controlled by player input. Movement of Type1 element causes disturbance in the natural flow of type 2 elements. Animation in infinite loop.

**Comment by prathimacode-hub** [comment] 2021-06-10 04:08
Wow, sounds exciting. The issue is assigned to you. @AK-Subodh

**Comment by prathimacode-hub** [comment] 2021-06-12 15:57
You hadn't updated your progress yet? @AK-Subodh

**Comment by AK-Subodh** [comment] 2021-06-12 16:16
> 
> 
> You hadn't updated your progress yet? @AK-Subodh

Mam, do I have to upload intermediate versions as well? Also, atmost how many days do we have for each issue? 
I need some more time to complete it.

**Comment by prathimacode-hub** [comment] 2021-06-12 16:27
Intermediate versions? I just pinged you to know the status. As I said, progress should be notified once in 2 days. Actually every PR gets 5 days time. Will you be able to do by then? @AK-Subodh

**Comment by AK-Subodh** [comment] 2021-06-12 16:39
> Intermediate versions? I just pinged you to know the status. As I said, progress should be notified once in 2 days. Actually every PR gets 5 days time. Will you be able to do by then? @AK-Subodh 

Yes mam! I'm working on it. I'll upload complete code by tomorrow this time.

Till now element1 has been designed. Code to test the motion of element2 is done. Definition of class for element2 and styling is remaining.

**Comment by prathimacode-hub** [comment] 2021-06-12 16:52
> > Intermediate versions? I just pinged you to know the status. As I said, progress should be notified once in 2 days. Actually every PR gets 5 days time. Will you be able to do by then? @AK-Subodh
> 
> Yes mam! I'm working on it. I'll upload complete code by tomorrow this time.
> 
> Till now element1 has been designed. Code to test the motion of element2 is done. Definition of class for element2 and styling is remaining.

That's perfect. Carry on with your task. @AK-Subodh

**Closed** 2021-06-15 03:59 UTC
Labels: Assigned, LGMSOC21
